export const PRODUCT_LIST_REQ = "PRODUCT_LIST_REQ";
export const PRODUCT_LIST_SUCCESS = "PRODUCT_LIST_REQ_SUCCESS";
export const PRODUCT_LIST_FAIL = "PRODUCT_LIST_REQ_FAIL";

export const PRODUCT_DETAILS_REQ = "PRODUCT_DETAILS_REQ";
export const PRODUCT_DETAILS_SUCCESS = "PRODUCT_DETAILS_REQ_SUCCESS";
export const PRODUCT_DETAILS_FAIL = "PRODUCT_DETAILS_REQ_FAIL";