export const REGISTER_REQ = "REGISTER_REQ"
export const REGISTER_SUCCESS = "REGISTER_SUCCESS"
export const REGISTER_FAILED = "REGISTER_FAIL"
export const CLEAR_REGISTER_ERROR = "CLEAR_REGISTER_ERROR"